library(tidyverse)
theme_set(theme_minimal())

##########################
########
#########################


naes_loess_08_df <- read_rds("data/tidy-naes-08-online.rds")%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	filter(!is.na(loser_first))%>%
	glimpse()

strong.model <- lm(strong_part ~ as.numeric(date), data = naes_loess_df)
summary(strong.model)

ggplot_loess_df <- cbind(naes_loess_df, predict(strong.model, interval = "confidence"))%>%
	glimpse()

# create and summarise model
cars.model <- lm(dist ~ speed, data = cars)
summary(cars.model) 

# add 'fit', 'lwr', and 'upr' columns to dataframe (generated by predict)
cars.predict <- cbind(cars, predict(cars.model, interval = 'confidence'))%>%
	glimpse()


partisan_loess_08 <- ggplot(naes_loess_08_df, aes(x = date, y = strong_part, color = loser_first)) +
	#	geom_point() +
	geom_smooth() +
	#	tidyquant::geom_ma(n = 27625, ratio = 1/7) +
	#stat_summary(aes(y = strong_part,group=1, colour=loser_first), fun.y=mean, geom="line",group=1) +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	facet_wrap(vars(pid3)) +
	scale_color_manual(values = c("Winner" = "#1E88E5", #colorblind safe palette
																"Loser" = "#D21C1C",
																"NA" = "#FFC107"))+
	labs(x = "Date",
			 y = "Strong Partisan",
			 color = "Vote Choice",
			 title = "LOESS Model of Partisanship Strength")
partisan_loess_08

ggsave("fig/gg-partisan-loess-08.png", plot = partisan_loess_08, width = 6, height = 4, units = "in")


naes_rolling <- naes_08_date%>%
	group_by(date, pid3, )%>%
	summarize


partisan_means_08 <- ggplot(ggplot_loess_df, aes(x = date, y = strong_part, color = loser_first)) +
	geom_point() +
	geom_smooth() +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	facet_wrap(vars(pid3))
partisan_means_08


# dif in dif of about#parallel trends association

# run a few models loess over dates

# Partisan Loess 2000
naes_2000_df <- read_rds("data/tidy-naes-2000.rds")%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	glimpse()


partisan_loess_00 <- ggplot(naes_2000_df, aes(x = date, y = strong_part, color = loser_first)) +
	#	geom_point() +
	geom_smooth() +
	#	tidyquant::geom_ma(n = 27625, ratio = 1/7) +
	#stat_summary(aes(y = strong_part,group=1, colour=loser_first), fun.y=mean, geom="line",group=1) +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	scale_color_manual(values = c("Winner" = "#1E88E5", #colorblind safe palette
																"Loser" = "#D21C1C",
																"Other/Third Party/Didn't Vote" = "#FFC107"))+
	facet_wrap(vars(pid3))
partisan_loess_00

ggsave("fig/partisan_loess_00.png", plot = partisan_loess_00, width = 6, height = 4, units = "in")



