library(tidyverse)
theme_set(theme_minimal())

##########################
########
#########################


naes_loess_08_df <- read_rds("data/tidy-naes-08-online.rds")%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	filter(!is.na(loser_first))%>%
	glimpse()

#MASS::polr(pid_str ~ )

levels(naes_loess_08_df$pid_str)
strong.model <- lm(strong_part ~ as.numeric(date), data = naes_loess_df)
summary(strong.model)

ggplot_loess_df <- cbind(naes_loess_df, predict(strong.model, interval = "confidence"))%>%
	glimpse()

# create and summarise model
cars.model <- lm(dist ~ speed, data = cars)
summary(cars.model) 

# add 'fit', 'lwr', and 'upr' columns to dataframe (generated by predict)
cars.predict <- cbind(cars, predict(cars.model, interval = 'confidence'))%>%
	glimpse()




partisan_loess_08 <- ggplot(naes_loess_08_df, aes(x = date, y = strong_part, color = loser_first)) +
	#	geom_point() +
	geom_smooth() +
	#	tidyquant::geom_ma(n = 27625, ratio = 1/7) +
	#stat_summary(aes(y = strong_part,group=1, colour=loser_first), fun.y=mean, geom="line",group=1) +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	facet_wrap(vars(pid3)) +
	scale_color_manual(values = c("Winner" = "#1E88E5", #colorblind safe palette
																"Loser" = "#D21C1C",
																"NA" = "#FFC107"))+
	labs(x = "Date",
			 y = "Strong Partisan",
			 color = "Vote Choice",
			 title = "LOESS Model of Partisanship Strength")
partisan_loess_08

ggsave("fig/gg-partisan-loess-08.png", plot = partisan_loess_08, width = 6, height = 4, units = "in")


naes_rolling <- naes_08_date%>%
	group_by(date, pid3, )%>%
	summarize


partisan_means_08 <- ggplot(ggplot_loess_df, aes(x = date, y = strong_part, color = loser_first)) +
	geom_point() +
	geom_smooth() +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	facet_wrap(vars(pid3))
partisan_means_08


# dif in dif of about#parallel trends association

# run a few models loess over dates

# Partisan Loess 2000
naes_2000_df <- read_rds("data/tidy-naes-2000.rds")%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	glimpse()


partisan_loess_00 <- ggplot(naes_2000_df, aes(x = date, y = strong_part, color = loser_first)) +
	#	geom_point() +
	geom_smooth() +
	#	tidyquant::geom_ma(n = 27625, ratio = 1/7) +
	#stat_summary(aes(y = strong_part,group=1, colour=loser_first), fun.y=mean, geom="line",group=1) +
	geom_vline(aes(xintercept = convention_end), linetype=4) + #last day of convention
	geom_vline(aes(xintercept = presumptive_date), linetype=1) + # day candidate becomes presumptive nominee
	geom_vline(aes(xintercept = general_election), linetype=2) + # general election
	scale_color_manual(values = c("Winner" = "#1E88E5", #colorblind safe palette
																"Loser" = "#D21C1C",
																"Other/Third Party/Didn't Vote" = "#FFC107"))+
	facet_wrap(vars(pid3))
partisan_loess_00

ggsave("fig/partisan_loess_00.png", plot = partisan_loess_00, width = 6, height = 4, units = "in")


naes_08_wave <- read_rds("data/tidy-naes-08.rds")%>%
	select(wave,
				 pid3,
				 loser_first,
				 strong_part,
				 wave)%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	group_by(wave, loser_first, pid3)%>%
	summarize(prop_strong = mean(strong_part, na.rm = TRUE))%>%
	mutate(wave = recode(wave,
											 "1" = "first",
											 "2" = "second",
											 "3" = "third",
											 "4" = "fourth",
											 "5" = "fifth",
											 "6" = "sixth"))%>%
	pivot_wider(names_from = wave,
							values_from = prop_strong)%>%
	glimpse()
	group_by(loser_first, pid3)%>%
	summarize(diff_prop = fifth - third)%>%
	glimpse()

naes_08_date <- read_rds("data/tidy-naes-08.rds")%>%
	select(convention_dummy,
				 pid3,
				 loser_first,
				 strong_part,
				 wave)%>%
	mutate(convention_dummy = recode(convention_dummy,
																	 'Post Convention' = "post_convention",
																	 'Pre Convention' = "pre_convention"))%>%
	filter(pid3 == "Republican" | pid3 == "Democrat")%>%
	group_by(convention_dummy, loser_first, pid3)%>%
	summarize(prop_strong = mean(strong_part, na.rm = TRUE))%>%
	pivot_wider(names_from = convention_dummy,
							values_from = prop_strong)%>%
	group_by(pid3, loser_first)%>%
	summarize(difference = post_convention - pre_convention)%>%
	pivot_wider(names_from = loser_first,
							values_from = difference)%>%
	group_by(pid3)%>%
	summarize(losers_dif_winners = loser - winner)%>%
	glimpse()
##########################
########
#########################





#testing the effect of losing the primary on pid_str

#Doing the strength change by group rather than paired. lots of right-censoring when paired
pid_str_dum_df <- read_rds("data/naes-08.rds")%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1,
					 first_choice_dum_1)%>%
	summarize(prop_strong_1_2 = mean(strong_part_dum_2, na.rm=TRUE) - mean(strong_part_dum_1, na.rm=TRUE),
						prop_strong_2_3 = mean(strong_part_dum_3, na.rm=TRUE) - mean(strong_part_dum_2, na.rm=TRUE),
						prop_strong_3_4 = mean(strong_part_dum_4, na.rm=TRUE) -mean(strong_part_dum_3, na.rm=TRUE))%>%
	pivot_longer(prop_strong_1_2:prop_strong_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()



pid_str_df <- read_rds("data/naes-08.rds")%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1,
					 first_choice_dum_1)%>%
	summarize(mean_change_pid_1_2 = mean(change_pid_1_2, na.rm=TRUE),
						mean_change_pid_2_3 = mean(change_pid_2_3, na.rm=TRUE),
						mean_change_pid_3_4 = mean(change_pid_3_4, na.rm=TRUE),
						se_change_pid_1_2 = sd(change_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_2_3 = sd(change_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_3_4 = sd(change_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_increase_change_pid_1_2 = mean(increase_pid_1_2, na.rm=TRUE),
						prop_increase_change_pid_2_3 = mean(increase_pid_2_3, na.rm=TRUE),
						prop_increase_change_pid_3_4 = mean(increase_pid_3_4, na.rm=TRUE),
						se_increase_change_pid_1_2 = sd(increase_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_2_3 = sd(increase_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_3_4 = sd(increase_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_decrease_change_pid_1_2 = mean(decrease_pid_1_2, na.rm=TRUE),
						prop_decrease_change_pid_2_3 = mean(decrease_pid_2_3, na.rm=TRUE),
						prop_decrease_change_pid_3_4 = mean(decrease_pid_3_4, na.rm=TRUE),
						se_decrease_change_pid_1_2 = sd(decrease_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_2_3 = sd(decrease_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_3_4 = sd(decrease_pid_3_4, na.rm = TRUE)/sqrt(length(.)),)%>%
	filter(!is.na(first_choice_dum_1) & !is.na(pid_3_1))%>%
	pivot_longer(mean_change_pid_1_2:se_decrease_change_pid_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	#	mutate(value = if_else(str_detect(waves, "mean"), "Mean", "SE"))%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()

#joining the vote choicedfs
joined_df <- left_join(pid_str_df, pid_str_dum_df)%>%
	glimpse()



# Party ID STR dummy
gg_three_wave_str <- ggplot(joined_df, aes(x = fct_rev(first_choice_dum_1), y = prop_strong, color = pid_3_1)) +
	geom_linerange(aes(ymin = prop_strong - 1.645*se_change, ymax = prop_strong + 1.645*se_change, color = pid_3_1), position = dodge) +
	geom_point(position = dodge) +
	geom_hline(yintercept = 0) +
	scale_color_manual(values = c("Democrat" = "dodgerblue3",
																"Republican" = "firebrick3")) +
	facet_wrap(vars(wave_presump)) +
	theme(legend.position = c(0.12, 0.2)) +
	coord_cartesian(ylim = c(-.5, .5)) +
	labs(title = "Strength of Party ID",
			 subtitle = "Change Between Waves",
			 x = "Primary Vote Choice",
			 y = "Mean Change Between Waves",
			 color = "Party ID at Wave 1") +
	scale_y_continuous(n.breaks = 10)
gg_three_wave_str

ggsave("fig/gg-three-wave-str.png", gg_three_wave_str, width = 4, height = 6, units = "in")


###########
########
###########


pid_str_dum_ug_df <- read_rds("data/naes-08.rds")%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1)%>%
	summarize(prop_strong_1_2 = mean(strong_part_dum_2, na.rm=TRUE) - mean(strong_part_dum_1, na.rm=TRUE),
						prop_strong_2_3 = mean(strong_part_dum_3, na.rm=TRUE) - mean(strong_part_dum_2, na.rm=TRUE),
						prop_strong_3_4 = mean(strong_part_dum_4, na.rm=TRUE) -mean(strong_part_dum_3, na.rm=TRUE))%>%
	pivot_longer(prop_strong_1_2:prop_strong_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()



pid_str_ug_df <- read_rds("data/naes-08.rds")%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1)%>%
	summarize(mean_change_pid_1_2 = mean(change_pid_1_2, na.rm=TRUE),
						mean_change_pid_2_3 = mean(change_pid_2_3, na.rm=TRUE),
						mean_change_pid_3_4 = mean(change_pid_3_4, na.rm=TRUE),
						se_change_pid_1_2 = sd(change_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_2_3 = sd(change_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_3_4 = sd(change_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_increase_change_pid_1_2 = mean(increase_pid_1_2, na.rm=TRUE),
						prop_increase_change_pid_2_3 = mean(increase_pid_2_3, na.rm=TRUE),
						prop_increase_change_pid_3_4 = mean(increase_pid_3_4, na.rm=TRUE),
						se_increase_change_pid_1_2 = sd(increase_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_2_3 = sd(increase_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_3_4 = sd(increase_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_decrease_change_pid_1_2 = mean(decrease_pid_1_2, na.rm=TRUE),
						prop_decrease_change_pid_2_3 = mean(decrease_pid_2_3, na.rm=TRUE),
						prop_decrease_change_pid_3_4 = mean(decrease_pid_3_4, na.rm=TRUE),
						se_decrease_change_pid_1_2 = sd(decrease_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_2_3 = sd(decrease_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_3_4 = sd(decrease_pid_3_4, na.rm = TRUE)/sqrt(length(.)),)%>%
	#	filter(!is.na(first_choice_dum_1) & !is.na(pid_3_1))%>%
	pivot_longer(mean_change_pid_1_2:se_decrease_change_pid_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	#	mutate(value = if_else(str_detect(waves, "mean"), "Mean", "SE"))%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()

joined_ug_df <- left_join(pid_str_ug_df, pid_str_dum_ug_df)%>%
	glimpse()


gg_ug_three_wave_str <- ggplot(joined_ug_df, aes(x = pid_3_1, y = prop_strong, color = pid_3_1)) +
	geom_linerange(aes(ymin = prop_strong - 1.645*se_strong, ymax = prop_strong + 1.645*se_strong, color = pid_3_1), position = dodge) +
	geom_point(position = dodge) +
	geom_hline(yintercept = 0) +
	scale_color_manual(values = c("Democrat" = "dodgerblue3",
																"Republican" = "firebrick3")) +
	facet_wrap(vars(wave_presump)) +
	theme(legend.position = c(0.12, 0.2)) +
	coord_cartesian(ylim = c(-.5, .5)) +
	labs(title = "Effect of Primary Victory on Strength of Party ID",
			 subtitle = "Change in Party Strength Between Waves",
			 x = "Primary Vote Choice",
			 y = "Mean Change in Partisanship Strength Between Waves",
			 color = "Party ID at Wave 1") +
	scale_y_continuous(n.breaks = 10)
gg_ug_three_wave_str

###############
#HERE
#############

naes_08 <- read_rds("data/naes-08.rds")%>%
	glimpse()
#testing the effect of losing the primary on pid_str

#Doing the strength change by group rather than paired. lots of right-censoring when paired
pid_str_boot_df <- data.frame(boot = 1:1000)%>%
	group_by(boot)%>%
	do(sample_n(naes_08, nrow(naes_08), replace = TRUE))%>% #creating 2000 new datasets of equal size to the original
	group_by(boot,
					 first_choice_dum_1,
					 pid_3_1)%>%
	summarize(prop_strong_1_2 = mean(strong_part_dum_2, na.rm=TRUE) - mean(strong_part_dum_1, na.rm=TRUE),
						prop_strong_2_3 = mean(strong_part_dum_3, na.rm=TRUE) - mean(strong_part_dum_2, na.rm=TRUE),
						prop_strong_3_4 = mean(strong_part_dum_4, na.rm=TRUE) - mean(strong_part_dum_3, na.rm=TRUE))%>%
	group_by(first_choice_dum_1,
					 pid_3_1)%>%
	summarize(se_strong_1_2 = sd(prop_strong_1_2, na.rm=TRUE),
						se_strong_2_3 =  sd(prop_strong_2_3, na.rm=TRUE),
						se_strong_3_4 =  sd(prop_strong_3_4, na.rm=TRUE))%>%
	pivot_longer(se_strong_1_2:se_strong_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()


pid_str_dum_df <- naes_08%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1,
					 first_choice_dum_1)%>%
	summarize(prop_strong_1_2 = mean(strong_part_dum_2, na.rm=TRUE) - mean(strong_part_dum_1, na.rm=TRUE),
						prop_strong_2_3 = mean(strong_part_dum_3, na.rm=TRUE) - mean(strong_part_dum_2, na.rm=TRUE),
						prop_strong_3_4 = mean(strong_part_dum_4, na.rm=TRUE) -mean(strong_part_dum_3, na.rm=TRUE))%>%
	pivot_longer(prop_strong_1_2:prop_strong_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()

joined_prop_str_df <- left_join(pid_str_dum_df, pid_str_boot_df)%>%
	glimpse()


pid_str_df <- read_rds("data/naes-08.rds")%>%
	filter(date_2 < presumptive_date & pid_3_1 == "Republican" | date_3 < presumptive_date & pid_3_1 == "Democrat")%>%
	group_by(pid_3_1,
					 first_choice_dum_1)%>%
	summarize(mean_change_pid_1_2 = mean(change_pid_1_2, na.rm=TRUE),
						mean_change_pid_2_3 = mean(change_pid_2_3, na.rm=TRUE),
						mean_change_pid_3_4 = mean(change_pid_3_4, na.rm=TRUE),
						se_change_pid_1_2 = sd(change_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_2_3 = sd(change_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_change_pid_3_4 = sd(change_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_increase_change_pid_1_2 = mean(increase_pid_1_2, na.rm=TRUE),
						prop_increase_change_pid_2_3 = mean(increase_pid_2_3, na.rm=TRUE),
						prop_increase_change_pid_3_4 = mean(increase_pid_3_4, na.rm=TRUE),
						se_increase_change_pid_1_2 = sd(increase_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_2_3 = sd(increase_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_increase_change_pid_3_4 = sd(increase_pid_3_4, na.rm = TRUE)/sqrt(length(.)),
						prop_decrease_change_pid_1_2 = mean(decrease_pid_1_2, na.rm=TRUE),
						prop_decrease_change_pid_2_3 = mean(decrease_pid_2_3, na.rm=TRUE),
						prop_decrease_change_pid_3_4 = mean(decrease_pid_3_4, na.rm=TRUE),
						se_decrease_change_pid_1_2 = sd(decrease_pid_1_2, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_2_3 = sd(decrease_pid_2_3, na.rm = TRUE)/sqrt(length(.)),
						se_decrease_change_pid_3_4 = sd(decrease_pid_3_4, na.rm = TRUE)/sqrt(length(.)),)%>%
	filter(!is.na(first_choice_dum_1) & !is.na(pid_3_1))%>%
	pivot_longer(mean_change_pid_1_2:se_decrease_change_pid_3_4, 
							 names_to = c(".value", "wave"), 
							 names_pattern="(^[a-z]+_[a-z]+).+(._.$)")%>%
	#	mutate(value = if_else(str_detect(waves, "mean"), "Mean", "SE"))%>%
	mutate(wave = recode(wave,
											 "1_2" = "Wave 1 to Wave 2",
											 "2_3" = "Wave 2 to Wave 3",
											 "3_4" = "Wave 3 to Wave 4"))%>%
	ungroup()%>%
	mutate(wave_presump = case_when(pid_3_1 == "Democrat" & wave == "Wave 2 to Wave 3" ~ "Before Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 1 to Wave 2" ~ "Before Presumptive",
																	pid_3_1 == "Democrat" & wave == "Wave 3 to Wave 4" ~ "After Presumptive",
																	pid_3_1 == "Republican" & wave == "Wave 2 to Wave 3" ~ "After Presumptive",
																	TRUE ~ NA_character_))%>%
	#	rename(prop_strong_change = prop)%>%
	filter(!is.na(wave_presump))%>%
	mutate(wave_presump = fct_rev(as.factor(wave_presump)))%>%
	glimpse()

#joining the vote choicedfs
joined_df <- left_join(pid_str_df, joined_prop_str_df)%>%
	glimpse()



# Party ID STR dummy
gg_three_wave_str <- ggplot(joined_df, aes(x = fct_rev(first_choice_dum_1), y = prop_strong, color = pid_3_1)) +
	geom_linerange(aes(ymin = prop_strong - 1.95*se_strong, ymax = prop_strong + 1.95*se_strong, color = pid_3_1), position = dodge) +
	geom_point(position = dodge) +
	geom_hline(yintercept = 0) +
	scale_color_manual(values = c("Democrat" = "dodgerblue3",
																"Republican" = "firebrick3")) +
	facet_wrap(vars(wave_presump)) +
	theme(legend.position = c(0.12, 0.2)) +
	coord_cartesian(ylim = c(-.3, .3)) +
	labs(title = "Change in Proportion of Strong Partisans",
			 subtitle = "Change Between Waves",
			 x = "Primary Vote Choice",
			 y = "Difference Between Waves",
			 color = "Party ID at Wave 1",
			 caption = "Bootstrapped 95% CIs") +
	scale_y_continuous(n.breaks = 10)
gg_three_wave_str
