library(tidyverse)
library(lubridate)

df_2020 <- import("data/raw/anes_timeseries_2020_csv_20210719.zip", which = "anes_timeseries_2020_csv_20210719.csv")%>%
	select(pid_7 = V201231x,
				 ft_dem = V201156,
				 ft_rep = V201157,
				 ideo_self = V201200, #1-7 lib con, -na
				 ideo_dem = V201206,
				 ideo_rep = V201207,
				 primary_vote = V201020,
				 primary_vote_choice_num = V201021,
				 dis_democ = V202440,
				 distrust_gov = V201233,
				 wrong_track_dum  = V201114,
				 gov_run_for_few_dum = V201234,
				 gov_care_post = V202212,
				 wealth_gap_larger = V201397,
				 weight = V200010a,
				 date = V203053)%>%
	mutate(pid_7_num = as.numeric(pid_7),
				 pid_7 = recode(pid_7, .default = NA_character_,
				 							 "1" = "Strong Democrat", 
				 							 "2" = "Weak Democrat", 
				 							 "3" = "Independent - Democrat", 
				 							 "4" = "Independent - Independent", 
				 							 "5" = "Independent - Republican", 
				 							 "6" = "Weak Republican", 
				 							 "7" = "Strong Republican"),
				 pid_7 = reorder(pid_7, pid_7_num), 
				 pid_3 = case_when(str_detect(pid_7, "Dem") ~ "Democrat", #counts leaning inds as partisan
				 									str_detect(pid_7, "Rep") ~ "Republican",
				 									str_detect(pid_7, "Ind") ~ "Independent",
				 									TRUE ~ NA_character_),
				 therm_dem = recode(ft_dem, .default = ft_dem,
				 								"-9" = NA_integer_,
				 								"998" = NA_integer_),
				 therm_rep = recode(ft_rep, .default = ft_rep,
				 								"-9" = NA_integer_,
				 								"998" = NA_integer_),
				 primary_vote_dum = as.numeric(recode(primary_vote, .default = NA_character_,
				 											"1" = "0",
				 											"2" = "1")),
				 primary_vote_choice_num = if_else(primary_vote_choice_num < 0, NA_integer_, primary_vote_choice_num),
				 primary_vote_choice = as.factor(recode(primary_vote_choice_num, .default = NA_character_,
				 														 "1" = "Joe Biden",
				 														 "2" = "Michael Bloomberg",
				 														 "3" = "Pete Buttigieg",
				 														 "4" = "Amy Klobuchar",
				 														 "5" = "Bernie Sanders",
				 														 "6" = "Elizabeth Warren",
				 														 "7" = "Other Democrat",
				 														 "8" = "Donald Trump",
				 														 "9" = "Other Republican",
				 														 "10" = "Someone Neither Dem. Nor Rep.")),
				 cand_party = case_when(primary_vote_choice_num <= 7 ~ "Democrat",
				 											 primary_vote_choice_num == 10 ~ "Other Party",
				 											 primary_vote_choice_num == 8 | primary_vote_choice_num == 9 ~ "Republican",
				 											 TRUE ~ NA_character_),
				 dis_democ_dum = as.integer(recode(dis_democ, .default = NA_character_,
				 									 "1" = "0",
				 									 "2" = "0",
				 									 "4" = "1",
				 									 "5" = "1")),
				 trust_gov = na_if(distrust_gov, -8),
				 trust_gov = na_if(distrust_gov, -9),
				 distrust_gov_dum = if_else(trust_gov >= 4, 1, 0),
				 trust_gov = recode(trust_gov, .default = NA_character_,
				 									 "1" =  "Always", # low values more trust
				 									 "2" = "Most of the Time",
				 									 "3" = "About Half the time",
				 									 "4" = "Some of the Time",
				 									 "5" = "Never"),
				 wrong_track_dum = as.integer(recode(wrong_track_dum, .default = NA_character_,
				 												 "1" = "0",
				 												 "2" = "1")), # 1 means R thinks things are on wrong track
				 gov_run_for_few_dum = as.integer(recode(gov_run_for_few_dum, .default = NA_character_,
				 														 "1" = "1",
				 														 "2" = "0")),
				 officials_dont_care_dum = as.integer(recode(gov_care_post, .default = NA_character_,
				 																 "1" = "1",
				 																 "2" = "1",
				 																 "3" = "0",
				 																 "4" = "0",
				 																 "5" = "0")),
				 therm_parties_mean = (ft_dem + ft_rep)/2,
				 therm_inparty = case_when(pid_3 == "Democrat" ~ ft_dem,
				 													pid_3 == "Republican" ~ ft_rep,
				 													pid_3 == "Independent" ~ NA_integer_,
				 													),
				 therm_outparty = case_when(pid_3 == "Democrat" ~ ft_rep,
				 													 pid_3 == "Republican" ~ ft_dem,
				 													 pid_3 == "Independent" ~ NA_integer_),
				 year = 2020,
				 below_50_qual_strict = case_when(therm_inparty < 50  ~ "cold",
				 																 therm_inparty >= 70 ~ "warm",
				 																 TRUE ~ NA_character_),
				 wealth_gap_larger_dum = as.numeric(recode(wealth_gap_larger, .default = NA_character_,
				 															 "1" = "1",
				 															 "2" = "0",
				 															 "3" = "0")),
				 date = ymd(date))%>% # 1 means R thinksgov run for a few  #pre interview date
	mutate(primary_vote_simple = case_when(pid_3 != cand_party ~ "Voted in Other Party Primary",
																				 pid_3 == "Democrat" & primary_vote_choice == "Joe Biden" ~ "Winner",
																				 pid_3 == "Republican" & primary_vote_choice == "Donald Trump" ~ "Winner",
																				 pid_3 != "Indpendent" & primary_vote_choice != "Didn't Vote" ~ "Loser",
																				 pid_3 != "Indpendent" & primary_vote_choice == "Didn't Vote" ~ "Didn't Vote",
																				 TRUE ~ NA_character_))%>%

	glimpse()%>%
	write_rds("data/tidy-2020.rds")%>%
	write_csv("data/tidy-2020.csv")
